### ISSUE TITLE
Editing raids in the raid list doesn't work + strange behaviour

### ISSUE THREAD

**Issue by Jutosa** [bbDKP/Raidplanner#62]
You can't edit an existing raid with the exception of the time.

Raid value and time bonus get discarded when you click "Update raid". Member who were signed up won't change.

BUT if you change the values in the text fields and then add an attendee without updating the new attendee uses the new settings but the time bonus is halfed. If you add another attendee it will use the halfed time.

Adding new attendees will continue to half the time bonus.

The time bonus is also not generated automatically when you first open the raid in the raid list. You have to either enter the value manually or change the time for it to refresh its value.

**Comment by Sajaki** [comment]
Raid value and time bonus is not editable once the raid is committed. that's intended.
